version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/app
    ports:
      - '27081:80'
    container_name: wxcloud_ciee-miniprogram
    labels:
      - wxPort=27082
      - hostPort=27081
      - wxcloud=ciee-miniprogram
      - role=container
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=WSGnnA83
      - MYSQL_ADDRESS=sh-cynosdbmysql-grp-buouyy58.sql.tencentcdb.com:26437
    depends_on:
      - redis
  redis:
    image: redis:alpine
    container_name: wxcloud_ciee-miniprogram_redis
    ports:
      - '6379:6379'
  celeryworker:
    build: .
    volumes:
      - .:/app
    command: /root/.local/bin/celery -A wxcloudrun worker --loglevel=info
    environment:
      - C_FORCE_ROOT=true
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=WSGnnA83
      - MYSQL_ADDRESS=sh-cynosdbmysql-grp-buouyy58.sql.tencentcdb.com:26437
    depends_on:
      - app
  celerybeat:
    build: .
    volumes:
      - .:/app
    command: /root/.local/bin/celery -A wxcloudrun beat --loglevel=info
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=WSGnnA83
      - MYSQL_ADDRESS=sh-cynosdbmysql-grp-buouyy58.sql.tencentcdb.com:26437
    depends_on:
      - app
networks:
  default:
    external:
      name: wxcb0
