# Generated by Django 3.2.8 on 2024-03-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50, verbose_name='招生方向')),
                ('total_academic_quota', models.IntegerField(default=0, verbose_name='学硕总指标')),
                ('total_professional_quota', models.IntegerField(default=0, verbose_name='北京专硕总指标')),
                ('total_professional_yt_quota', models.IntegerField(default=0, verbose_name='烟台专硕总指标')),
                ('total_doctor_quota', models.IntegerField(default=0, verbose_name='博士总指标')),
                ('used_academic_quota', models.IntegerField(default=0, verbose_name='学硕已用指标')),
                ('used_professional_quota', models.IntegerField(default=0, verbose_name='北京专硕已用指标')),
                ('used_professional_yt_quota', models.IntegerField(default=0, verbose_name='烟台专硕已用指标')),
                ('used_doctor_quota', models.IntegerField(default=0, verbose_name='博士已用指标')),
            ],
            options={
                'verbose_name': '招生方向',
                'verbose_name_plural': '招生方向',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50, verbose_name='专业名称')),
                ('subject_code', models.CharField(max_length=10, verbose_name='专业代码')),
                ('subject_type', models.IntegerField(choices=[[0, '专硕'], [1, '学硕'], [2, '博士']], verbose_name='专业所属类别')),
                ('subject_department', models.ManyToManyField(related_name='subjects', to='Enrollment_Manage.Department', verbose_name='可选该专业的方向')),
            ],
            options={
                'verbose_name': '专业',
                'verbose_name_plural': '专业',
            },
        ),
    ]
