# Generated by Django 3.2.8 on 2025-09-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enrollment_Manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='total_admission_quota',
            field=models.PositiveIntegerField(default=0, verbose_name='总招生人数'),
        ),
    ]
