from django.urls import path

from .views import (
    DashboardAuditLogDetailView,
    DashboardAuditLogListView,
    DashboardAlternateListView,
    DashboardAlternateBatchDeleteView,
    DashboardAlternatePromoteNextView,
    DashboardAdmissionBatchDetailView,
    DashboardAdmissionBatchListView,
    DashboardAvailableStudentDisplaySettingView,
    DashboardChoiceBatchDeleteView,
    DashboardChoiceListView,
    DashboardStudentChoiceBehaviorListView,
    DashboardChoiceCancelApprovedView,
    DashboardChoiceCancelWaitingGiveupView,
    DashboardChoiceRejectWaitingNoQuotaView,
    DashboardDepartmentListView,
    DashboardDepartmentBatchDeleteView,
    DashboardDepartmentQuotaUpdateView,
    DashboardDoctorQuotaClearAllView,
    DashboardDoctorQuotaDetailView,
    DashboardDoctorQuotaListView,
    DashboardFileDownloadUrlView,
    DashboardGiveupListView,
    DashboardGiveupBatchDeleteView,
    DashboardLoginView,
    DashboardLogoutView,
    DashboardMeView,
    DashboardProfessorDetailView,
    DashboardProfessorImportDoctorQuotaView,
    DashboardProfessorHeatDetailView,
    DashboardProfessorHeatListView,
    DashboardProfessorHeatSettingView,
    DashboardProfessorImportMasterQuotaView,
    DashboardProfessorListView,
    DashboardProfessorBatchDeleteView,
    DashboardProfessorResetPasswordView,
    DashboardProfessorResetQuotaView,
    DashboardProfessorResetSelectionStatusView,
    DashboardReviewRecordBatchApproveView,
    DashboardReviewRecordBatchDeleteView,
    DashboardReviewRecordDetailView,
    DashboardReviewRecordListView,
    DashboardSharedQuotaPoolDetailView,
    DashboardSharedQuotaPoolClearAllView,
    DashboardSharedQuotaPoolListView,
    DashboardSelectionTimeListView,
    DashboardSessionDetailView,
    DashboardSessionListView,
    DashboardStatsView,
    DashboardTokenDetailView,
    DashboardTokenListView,
    DashboardTokenRegenerateView,
    DashboardUserDetailView,
    DashboardUserListView,
    DashboardMasterQuotaClearAllView,
    DashboardMasterQuotaDetailView,
    DashboardMasterQuotaListView,
    DashboardStudentDetailView,
    DashboardStudentListView,
    DashboardStudentBatchDeleteView,
    DashboardStudentBatchDownloadView,
    DashboardStudentImportView,
    DashboardStudentPromoteAlternateView,
    DashboardStudentRegenerateSignatureTableView,
    DashboardStudentResetPasswordView,
    DashboardStudentToggleLoginView,
    DashboardStudentToggleSelectionDisplayView,
    DashboardStudentRevokeGiveupView,
    DashboardSubjectListView,
    DashboardSubjectBatchDeleteView,
    DashboardSubjectQuotaUpdateView,
    DashboardWeChatAccountDetailView,
    DashboardWeChatAccountListView,
    DashboardChoiceExportSelectedView,
)


urlpatterns = [
    path('auth/login/', DashboardLoginView.as_view(), name='dashboard-login'),
    path('auth/logout/', DashboardLogoutView.as_view(), name='dashboard-logout'),
    path('auth/me/', DashboardMeView.as_view(), name='dashboard-me'),
    path('auth/sessions/', DashboardSessionListView.as_view(), name='dashboard-sessions'),
    path('auth/sessions/<str:key>/', DashboardSessionDetailView.as_view(), name='dashboard-session-detail'),
    path('audit-logs/', DashboardAuditLogListView.as_view(), name='dashboard-audit-logs'),
    path('audit-logs/<int:pk>/', DashboardAuditLogDetailView.as_view(), name='dashboard-audit-log-detail'),
    path('users/', DashboardUserListView.as_view(), name='dashboard-users'),
    path('users/<int:pk>/', DashboardUserDetailView.as_view(), name='dashboard-user-detail'),
    path('files/download-url/', DashboardFileDownloadUrlView.as_view(), name='dashboard-file-download-url'),
    path('dashboard/stats/', DashboardStatsView.as_view(), name='dashboard-stats'),
    path('professors/', DashboardProfessorListView.as_view(), name='dashboard-professors'),
    path('professor-heat/', DashboardProfessorHeatListView.as_view(), name='dashboard-professor-heat'),
    path('professor-heat/settings/', DashboardProfessorHeatSettingView.as_view(), name='dashboard-professor-heat-setting'),
    path('professor-heat/<int:pk>/', DashboardProfessorHeatDetailView.as_view(), name='dashboard-professor-heat-detail'),
    path('professors/<int:pk>/', DashboardProfessorDetailView.as_view(), name='dashboard-professor-detail'),
    path('professors/actions/batch-delete/', DashboardProfessorBatchDeleteView.as_view(), name='dashboard-professors-batch-delete'),
    path('professors/actions/reset-password/', DashboardProfessorResetPasswordView.as_view(), name='dashboard-professors-reset-password'),
    path('professors/actions/reset-quota/', DashboardProfessorResetQuotaView.as_view(), name='dashboard-professors-reset-quota'),
    path('professors/actions/reset-selection-status/', DashboardProfessorResetSelectionStatusView.as_view(), name='dashboard-professors-reset-selection-status'),
    path('professors/import-master-quota/', DashboardProfessorImportMasterQuotaView.as_view(), name='dashboard-professors-import-master-quota'),
    path('professors/import-doctor-quota/', DashboardProfessorImportDoctorQuotaView.as_view(), name='dashboard-professors-import-doctor-quota'),
    path('students/', DashboardStudentListView.as_view(), name='dashboard-students'),
    path('student-display-settings/', DashboardAvailableStudentDisplaySettingView.as_view(), name='dashboard-student-display-settings'),
    path('students/import/', DashboardStudentImportView.as_view(), name='dashboard-students-import'),
    path('students/<int:pk>/', DashboardStudentDetailView.as_view(), name='dashboard-student-detail'),
    path('students/actions/batch-delete/', DashboardStudentBatchDeleteView.as_view(), name='dashboard-students-batch-delete'),
    path('students/actions/batch-download/', DashboardStudentBatchDownloadView.as_view(), name='dashboard-students-batch-download'),
    path('students/actions/reset-password/', DashboardStudentResetPasswordView.as_view(), name='dashboard-students-reset-password'),
    path('students/actions/regenerate-signature-table/', DashboardStudentRegenerateSignatureTableView.as_view(), name='dashboard-students-regenerate-signature-table'),
    path('students/actions/toggle-login/', DashboardStudentToggleLoginView.as_view(), name='dashboard-students-toggle-login'),
    path('students/actions/toggle-selection-display/', DashboardStudentToggleSelectionDisplayView.as_view(), name='dashboard-students-toggle-selection-display'),
    path('students/<int:pk>/promote-alternate/', DashboardStudentPromoteAlternateView.as_view(), name='dashboard-student-promote-alternate'),
    path('students/<int:pk>/revoke-giveup/', DashboardStudentRevokeGiveupView.as_view(), name='dashboard-student-revoke-giveup'),
    path('choices/', DashboardChoiceListView.as_view(), name='dashboard-choices'),
    path('student-choice-behaviors/', DashboardStudentChoiceBehaviorListView.as_view(), name='dashboard-student-choice-behaviors'),
    path('choices/actions/batch-delete/', DashboardChoiceBatchDeleteView.as_view(), name='dashboard-choices-batch-delete'),
    path('choices/export-selected/', DashboardChoiceExportSelectedView.as_view(), name='dashboard-choices-export-selected'),
    path('choices/actions/cancel-approved/', DashboardChoiceCancelApprovedView.as_view(), name='dashboard-choices-cancel-approved'),
    path('choices/actions/reject-waiting-no-quota/', DashboardChoiceRejectWaitingNoQuotaView.as_view(), name='dashboard-choices-reject-waiting-no-quota'),
    path('choices/actions/cancel-waiting-giveup/', DashboardChoiceCancelWaitingGiveupView.as_view(), name='dashboard-choices-cancel-waiting-giveup'),
    path('review-records/', DashboardReviewRecordListView.as_view(), name='dashboard-review-records'),
    path('review-records/<int:pk>/', DashboardReviewRecordDetailView.as_view(), name='dashboard-review-record-detail'),
    path('review-records/actions/batch-delete/', DashboardReviewRecordBatchDeleteView.as_view(), name='dashboard-review-record-batch-delete'),
    path('review-records/actions/batch-approve/', DashboardReviewRecordBatchApproveView.as_view(), name='dashboard-review-record-batch-approve'),
    path('selection-times/', DashboardSelectionTimeListView.as_view(), name='dashboard-selection-times'),
    path('admission-batches/', DashboardAdmissionBatchListView.as_view(), name='dashboard-admission-batches'),
    path('admission-batches/<int:pk>/', DashboardAdmissionBatchDetailView.as_view(), name='dashboard-admission-batch-detail'),
    path('departments/', DashboardDepartmentListView.as_view(), name='dashboard-departments'),
    path('departments/actions/batch-delete/', DashboardDepartmentBatchDeleteView.as_view(), name='dashboard-departments-batch-delete'),
    path('departments/<int:pk>/quota/', DashboardDepartmentQuotaUpdateView.as_view(), name='dashboard-department-quota-update'),
    path('subjects/', DashboardSubjectListView.as_view(), name='dashboard-subjects'),
    path('subjects/actions/batch-delete/', DashboardSubjectBatchDeleteView.as_view(), name='dashboard-subjects-batch-delete'),
    path('subjects/<int:pk>/quota/', DashboardSubjectQuotaUpdateView.as_view(), name='dashboard-subject-quota-update'),
    path('doctor-quotas/', DashboardDoctorQuotaListView.as_view(), name='dashboard-doctor-quotas'),
    path('doctor-quotas/<int:pk>/', DashboardDoctorQuotaDetailView.as_view(), name='dashboard-doctor-quota-detail'),
    path('doctor-quotas/actions/clear-all/', DashboardDoctorQuotaClearAllView.as_view(), name='dashboard-doctor-quotas-clear-all'),
    path('master-quotas/', DashboardMasterQuotaListView.as_view(), name='dashboard-master-quotas'),
    path('master-quotas/<int:pk>/', DashboardMasterQuotaDetailView.as_view(), name='dashboard-master-quota-detail'),
    path('master-quotas/actions/clear-all/', DashboardMasterQuotaClearAllView.as_view(), name='dashboard-master-quotas-clear-all'),
    path('shared-quota-pools/', DashboardSharedQuotaPoolListView.as_view(), name='dashboard-shared-quota-pools'),
    path('shared-quota-pools/<int:pk>/', DashboardSharedQuotaPoolDetailView.as_view(), name='dashboard-shared-quota-pool-detail'),
    path('shared-quota-pools/actions/clear-all/', DashboardSharedQuotaPoolClearAllView.as_view(), name='dashboard-shared-quota-pools-clear-all'),
    path('wechat-accounts/', DashboardWeChatAccountListView.as_view(), name='dashboard-wechat-accounts'),
    path('wechat-accounts/<int:pk>/', DashboardWeChatAccountDetailView.as_view(), name='dashboard-wechat-account-detail'),
    path('tokens/', DashboardTokenListView.as_view(), name='dashboard-tokens'),
    path('tokens/<str:key>/', DashboardTokenDetailView.as_view(), name='dashboard-token-detail'),
    path('tokens/<str:key>/regenerate/', DashboardTokenRegenerateView.as_view(), name='dashboard-token-regenerate'),
    path('alternates/', DashboardAlternateListView.as_view(), name='dashboard-alternates'),
    path('alternates/actions/batch-delete/', DashboardAlternateBatchDeleteView.as_view(), name='dashboard-alternates-batch-delete'),
    path('alternates/promote-next/', DashboardAlternatePromoteNextView.as_view(), name='dashboard-alternates-promote-next'),
    path('giveups/', DashboardGiveupListView.as_view(), name='dashboard-giveups'),
    path('giveups/actions/batch-delete/', DashboardGiveupBatchDeleteView.as_view(), name='dashboard-giveups-batch-delete'),
]
