# Generated by Django 3.2.8 on 2023-08-13 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50, verbose_name='系名称')),
                ('total_quota', models.IntegerField(default=0, verbose_name='总指标')),
            ],
            options={
                'verbose_name': '院系',
                'verbose_name_plural': '院系',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('candidate_number', models.CharField(max_length=20, unique=True, verbose_name='准考证号')),
                ('major', models.CharField(max_length=100, verbose_name='报考专业')),
                ('specialty_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='专业代码')),
                ('is_selected', models.BooleanField(default=False, verbose_name='是否选好导师')),
                ('student_type', models.CharField(choices=[['1', '硕士推免生'], ['2', '硕士统考生'], ['3', '博士统考生']], max_length=1, verbose_name='学生类型')),
                ('study_mode', models.BooleanField(choices=[[True, '全日制'], [False, '非全日制']], default=True, max_length=20, verbose_name='学习方式')),
                ('resume', models.FileField(blank=True, null=True, upload_to='students/static/resumes/', verbose_name='简历')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('initial_exam_score', models.FloatField(blank=True, null=True)),
                ('secondary_exam_score', models.FloatField(blank=True, null=True)),
                ('initial_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('secondary_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('final_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('user_name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='导师姓名')),
                ('name_fk_search', models.CharField(max_length=100, null=True, verbose_name='导师(搜索专用)')),
                ('teacher_identity_id', models.CharField(max_length=20, verbose_name='导师工号')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('research_areas', models.TextField(blank=True, null=True)),
                ('academic_quota', models.IntegerField(blank=True, default=0)),
                ('professional_quota', models.IntegerField(blank=True, default=0)),
                ('doctor_quota', models.IntegerField(blank=True, default=0)),
                ('proposed_quota_approved', models.BooleanField(default=False, verbose_name='指标审核')),
                ('have_qualification', models.BooleanField(default=True, verbose_name='招生资格')),
                ('remaining_quota', models.IntegerField(default=0)),
                ('personal_page', models.URLField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='professors/')),
                ('department_position', models.IntegerField(choices=[[0, '非审核人'], [2, '系主任'], [1, '副主任']], default=0)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Professor_Student_Manage.department', verbose_name='所属系')),
                ('user_name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '导师',
                'verbose_name_plural': '导师',
            },
        ),
    ]
