# Generated by Django 3.2.8 on 2023-08-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name_fk_search',
            field=models.CharField(max_length=100, null=True, verbose_name='学生(搜索专用)'),
        ),
    ]
