# Generated by Django 3.2.8 on 2023-08-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0003_student_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='简历'),
        ),
    ]
