# Generated by Django 3.2.8 on 2023-08-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0004_alter_student_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='postgraduate_type',
            field=models.CharField(blank=True, choices=[['1', '专业型'], ['2', '学术型'], ['3', '其它']], max_length=1, null=True, verbose_name='研究生类型'),
        ),
    ]
