# Generated by Django 3.2.8 on 2023-08-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0005_student_postgraduate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='postgraduate_type',
            field=models.CharField(choices=[['1', '专业型'], ['2', '学术型'], ['3', '其它']], max_length=1, verbose_name='研究生类型'),
        ),
    ]
