# Generated by Django 3.2.8 on 2023-08-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0006_alter_student_postgraduate_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='photo',
        ),
        migrations.AddField(
            model_name='professor',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
    ]
