# Generated by Django 3.2.8 on 2023-09-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0008_auto_20230829_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
