# Generated by Django 3.2.8 on 2023-09-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0009_auto_20230912_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='avatar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='student',
            name='resume',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='简历'),
        ),
    ]
