# Generated by Django 3.2.8 on 2023-09-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0010_auto_20230913_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='personal_page',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
