# Generated by Django 3.2.8 on 2023-09-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0011_alter_professor_personal_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='identify_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='身份证号'),
        ),
        migrations.AddField(
            model_name='student',
            name='major_direction',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='报考专业方向'),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(max_length=100, verbose_name='申请专业'),
        ),
    ]
