# Generated by Django 3.2.8 on 2023-09-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0012_auto_20230925_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='major_direction',
            field=models.CharField(blank=True, choices=[['1', '电气工程'], ['2', '农业工程'], ['3', '计算机学科方向一'], ['4', '计算机学科方向二'], ['5', '计算机学科方向三'], ['6', '计算机学科方向四']], max_length=100, null=True, verbose_name='报考专业方向'),
        ),
    ]
