# Generated by Django 3.2.8 on 2023-09-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0014_alter_student_major_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='academic_quota',
            field=models.IntegerField(blank=True, default=0, verbose_name='学硕剩余名额'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='avatar',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='照片下载地址'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='department_position',
            field=models.IntegerField(choices=[[0, '非审核人'], [1, '方向审核人']], default=0, verbose_name='是否是审核人'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='doctor_quota',
            field=models.IntegerField(blank=True, default=0, verbose_name='博士剩余名额'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='导师邮箱'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='personal_page',
            field=models.CharField(blank=True, max_length=300, verbose_name='个人介绍'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='professional_quota',
            field=models.IntegerField(blank=True, default=0, verbose_name='专硕剩余名额'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='remaining_quota',
            field=models.IntegerField(default=0, verbose_name='总剩余名额'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='research_areas',
            field=models.TextField(blank=True, null=True, verbose_name='研究方向'),
        ),
    ]
