# Generated by Django 3.2.8 on 2023-09-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0015_auto_20230925_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='used_quota',
            field=models.IntegerField(default=0, verbose_name='总指标'),
        ),
    ]
