# Generated by Django 3.2.8 on 2023-09-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0016_department_used_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='total_academic_quota',
            field=models.IntegerField(default=0, verbose_name='学硕总指标'),
        ),
        migrations.AddField(
            model_name='department',
            name='total_doctor_quota',
            field=models.IntegerField(default=0, verbose_name='博士总指标'),
        ),
        migrations.AddField(
            model_name='department',
            name='total_professional_quota',
            field=models.IntegerField(default=0, verbose_name='专硕总指标'),
        ),
        migrations.AddField(
            model_name='department',
            name='used_academic_quota',
            field=models.IntegerField(default=0, verbose_name='学硕已用指标'),
        ),
        migrations.AddField(
            model_name='department',
            name='used_doctor_quota',
            field=models.IntegerField(default=0, verbose_name='博士已用指标'),
        ),
        migrations.AddField(
            model_name='department',
            name='used_professional_quota',
            field=models.IntegerField(default=0, verbose_name='专硕已用指标'),
        ),
        migrations.AlterField(
            model_name='department',
            name='total_quota',
            field=models.IntegerField(default=0, verbose_name='学硕总指标'),
        ),
        migrations.AlterField(
            model_name='department',
            name='used_quota',
            field=models.IntegerField(default=0, verbose_name='专硕总指标'),
        ),
    ]
