# Generated by Django 3.2.8 on 2023-09-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0018_auto_20230925_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='total_quota',
            field=models.IntegerField(blank=True, null=True, verbose_name='学硕总指标'),
        ),
        migrations.AlterField(
            model_name='department',
            name='used_quota',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='专硕总指标'),
        ),
    ]
