# Generated by Django 3.2.8 on 2023-09-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0019_auto_20230925_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='total_quota',
        ),
        migrations.RemoveField(
            model_name='department',
            name='used_quota',
        ),
    ]
