# Generated by Django 3.2.8 on 2024-02-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0022_auto_20230925_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='professional_quota',
        ),
        migrations.AddField(
            model_name='professor',
            name='professional_bj_quota',
            field=models.IntegerField(blank=True, default=0, verbose_name='专硕剩余名额'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='department_position',
            field=models.IntegerField(choices=[[0, '非审核人'], [1, '方向审核人(北京)'], [2, '方向审核人(烟台)']], default=0, verbose_name='是否是审核人'),
        ),
        migrations.AlterField(
            model_name='student',
            name='postgraduate_type',
            field=models.CharField(choices=[['1', '专业型(北京)'], ['2', '学术型'], ['3', '博士'], ['4', '专业型(烟台)']], max_length=1, verbose_name='研究生类型'),
        ),
    ]
