# Generated by Django 3.2.8 on 2024-02-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0023_auto_20240227_0600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='professional_bj_quota',
            new_name='professional_quota',
        ),
        migrations.AddField(
            model_name='professor',
            name='professional_yt_quota',
            field=models.IntegerField(blank=True, default=0, verbose_name='专硕(烟台)剩余名额'),
        ),
    ]
