# Generated by Django 3.2.8 on 2024-03-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0025_alter_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='total_professional_yt_quota',
            field=models.IntegerField(default=0, verbose_name='烟台专硕总指标'),
        ),
        migrations.AddField(
            model_name='department',
            name='used_professional_yt_quota',
            field=models.IntegerField(default=0, verbose_name='烟台专硕已用指标'),
        ),
        migrations.AlterField(
            model_name='department',
            name='total_professional_quota',
            field=models.IntegerField(default=0, verbose_name='北京专硕总指标'),
        ),
        migrations.AlterField(
            model_name='department',
            name='used_professional_quota',
            field=models.IntegerField(default=0, verbose_name='北京专硕已用指标'),
        ),
    ]
