# Generated by Django 3.2.8 on 2024-03-04 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0026_auto_20240304_0500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratory_name', models.CharField(max_length=50, verbose_name='烟台实验室')),
                ('Laboratory_quota', models.IntegerField(default=0, verbose_name='实验室总指标')),
                ('laboratory_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Professor_Student_Manage.professor', verbose_name='实验室负责人')),
            ],
            options={
                'verbose_name': '烟台实验室',
                'verbose_name_plural': '烟台实验室',
            },
        ),
    ]
