# Generated by Django 3.2.8 on 2024-03-04 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0027_laboratory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory',
            name='laboratory_leader',
        ),
        migrations.AddField(
            model_name='professor',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Professor_Student_Manage.laboratory', verbose_name='所属实验室'),
        ),
    ]
