# Generated by Django 3.2.8 on 2024-03-04 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0028_auto_20240304_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='laboratory_leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_of', to='Professor_Student_Manage.professor', verbose_name='实验室负责人'),
        ),
    ]
