# Generated by Django 3.2.8 on 2024-03-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0029_laboratory_laboratory_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='laboratory_member',
            field=models.ManyToManyField(related_name='member_laboratory', to='Professor_Student_Manage.Professor'),
        ),
    ]
