# Generated by Django 3.2.8 on 2024-03-04 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0030_laboratory_laboratory_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory',
            name='laboratory_member',
        ),
    ]
