# Generated by Django 3.2.8 on 2024-03-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0032_wechataccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wechataccount',
            options={'verbose_name': '微信账号绑定', 'verbose_name_plural': '微信账号绑定'},
        ),
        migrations.RemoveField(
            model_name='professor',
            name='laboratory',
        ),
        migrations.AddField(
            model_name='wechataccount',
            name='session_key',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Laboratory',
        ),
    ]
