# Generated by Django 3.2.8 on 2024-03-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0035_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_department',
            field=models.ManyToManyField(related_name='subjects', to='Professor_Student_Manage.Department', verbose_name='可选该专业的方向'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.IntegerField(choices=[[0, '专硕'], [1, '学硕'], [2, '博士']], verbose_name='专业所属类别'),
        ),
    ]
