# Generated by Django 3.2.8 on 2024-03-05 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0036_auto_20240305_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='major',
        ),
        migrations.RemoveField(
            model_name='student',
            name='major_direction',
        ),
        migrations.RemoveField(
            model_name='student',
            name='specialty_code',
        ),
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Professor_Student_Manage.subject', verbose_name='报考专业'),
        ),
    ]
