# Generated by Django 3.2.8 on 2024-03-05 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0037_auto_20240305_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject_name',
            new_name='subject_designation',
        ),
    ]
