# Generated by Django 3.2.8 on 2024-03-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0038_rename_subject_name_subject_subject_designation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='SubjectManage',
        ),
    ]
