# Generated by Django 3.2.8 on 2024-03-05 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0039_rename_subject_subjectmanage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubjectManage',
            new_name='Subject',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subject_designation',
            new_name='subject_name',
        ),
    ]
