# Generated by Django 3.2.8 on 2024-03-06 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Enrollment_Manage', '0001_initial'),
        ('Professor_Student_Manage', '0040_auto_20240305_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='subject_department',
        ),
        migrations.AlterField(
            model_name='professor',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enrollment_Manage.department', verbose_name='所属招生方向'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='proposed_quota_approved',
            field=models.BooleanField(default=False, verbose_name='设置指标'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Enrollment_Manage.subject', verbose_name='报考专业'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
