# Generated by Django 3.2.8 on 2024-03-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0041_auto_20240306_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='postgraduate_type',
            field=models.IntegerField(choices=[[1, '专业型(北京)'], [2, '学术型'], [3, '博士'], [4, '专业型(烟台)']], max_length=1, verbose_name='研究生类型'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_type',
            field=models.IntegerField(choices=[[1, '硕士推免生'], [2, '硕士统考生'], [3, '博士统考生']], verbose_name='学生类型'),
        ),
    ]
