# Generated by Django 3.2.8 on 2024-03-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enrollment_Manage', '0001_initial'),
        ('Professor_Student_Manage', '0043_alter_student_postgraduate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='enroll_subject',
            field=models.ManyToManyField(related_name='subjects', to='Enrollment_Manage.Subject', verbose_name='招生专业'),
        ),
    ]
