# Generated by Django 3.2.8 on 2024-09-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0045_professor_contact_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='signature_temp',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='签名临时下载地址'),
        ),
        migrations.AddField(
            model_name='student',
            name='signature_table',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='导师意向表下载地址'),
        ),
        migrations.AddField(
            model_name='student',
            name='signature_temp',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='签名临时下载地址'),
        ),
    ]
