# Generated by Django 3.2.8 on 2024-09-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0047_student_signature_table_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='signature_table_review_status',
            field=models.IntegerField(choices=[[1, '已同意'], [2, '已拒绝'], [3, '待审核'], [4, '未提交']], default=4, verbose_name='导师意向表审核状态'),
        ),
    ]
