# Generated by Django 3.2.8 on 2025-03-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0048_alter_student_signature_table_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='giveup_signature_table',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='放弃说明表下载地址'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_giveup',
            field=models.BooleanField(default=False, verbose_name='是否放弃拟录取'),
        ),
        migrations.AddField(
            model_name='student',
            name='signature_table_professor_signatured',
            field=models.BooleanField(default=False, verbose_name='导师签署导师意向表'),
        ),
        migrations.AddField(
            model_name='student',
            name='signature_table_student_signatured',
            field=models.BooleanField(default=False, verbose_name='学生签署导师意向表'),
        ),
    ]
