# Generated by Django 3.2.8 on 2025-03-18 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0049_auto_20250318_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='signature_table_professor_signatured',
        ),
        migrations.RemoveField(
            model_name='student',
            name='signature_table_student_signatured',
        ),
    ]
