# Generated by Django 3.2.8 on 2025-03-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0050_auto_20250318_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='signature_table_professor_signatured',
            field=models.BooleanField(default=False, verbose_name='导师签署导师意向表'),
        ),
        migrations.AddField(
            model_name='student',
            name='signature_table_student_signatured',
            field=models.BooleanField(default=False, verbose_name='学生签署导师意向表'),
        ),
    ]
