# Generated by Django 3.2.8 on 2025-03-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0051_auto_20250318_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='contact_details',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='personal_page',
            field=models.CharField(blank=True, max_length=500, verbose_name='个人介绍'),
        ),
    ]
