# Generated by Django 3.2.8 on 2025-03-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0052_auto_20250324_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='professor_title',
            field=models.CharField(default='副教授', max_length=10, verbose_name='导师职称'),
        ),
    ]
