# Generated by Django 3.2.8 on 2025-03-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0053_professor_professor_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='website_order',
            field=models.IntegerField(default=0, verbose_name='官网排序号'),
        ),
    ]
