# Generated by Django 3.2.8 on 2025-04-29 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Enrollment_Manage', '0001_initial'),
        ('Professor_Student_Manage', '0054_professor_website_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorDoctorQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quota', models.IntegerField(default=0, verbose_name='总招生名额')),
                ('used_quota', models.IntegerField(default=0, verbose_name='已用名额')),
                ('remaining_quota', models.IntegerField(default=0, verbose_name='剩余名额')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_quotas', to='Professor_Student_Manage.professor', verbose_name='导师')),
                ('subject', models.ForeignKey(limit_choices_to={'subject_type': 2}, on_delete=django.db.models.deletion.CASCADE, to='Enrollment_Manage.subject', verbose_name='博士专业')),
            ],
            options={
                'verbose_name': '导师博士专业名额',
                'verbose_name_plural': '导师博士专业名额',
                'unique_together': {('professor', 'subject')},
            },
        ),
    ]
