# Generated by Django 3.2.8 on 2025-09-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0055_professordoctorquota'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_alternate',
            field=models.BooleanField(default=False, verbose_name='是否候补'),
        ),
        migrations.AlterField(
            model_name='student',
            name='final_rank',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='总排名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='initial_exam_score',
            field=models.FloatField(blank=True, null=True, verbose_name='初试成绩'),
        ),
        migrations.AlterField(
            model_name='student',
            name='initial_rank',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='初试排名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='secondary_exam_score',
            field=models.FloatField(blank=True, null=True, verbose_name='复试成绩'),
        ),
        migrations.AlterField(
            model_name='student',
            name='secondary_rank',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='复试排名'),
        ),
    ]
