# Generated by Django 3.2.8 on 2025-09-16 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0056_auto_20250916_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_alternate',
        ),
    ]
