# Generated by Django 3.2.8 on 2025-09-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0057_remove_student_is_alternate'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_alternate',
            field=models.BooleanField(default=False, verbose_name='是否候补'),
        ),
    ]
