# Generated by Django 3.2.8 on 2025-09-17 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Enrollment_Manage', '0001_initial'),
        ('Professor_Student_Manage', '0058_student_is_alternate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorMasterQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quota', models.IntegerField(default=0, verbose_name='硕士总招生名额')),
                ('beijing_used_quota', models.IntegerField(default=0, verbose_name='北京已用名额')),
                ('beijing_remaining_quota', models.IntegerField(default=0, verbose_name='北京剩余名额')),
                ('yantai_used_quota', models.IntegerField(default=0, verbose_name='烟台已用名额')),
                ('yantai_remaining_quota', models.IntegerField(default=0, verbose_name='烟台剩余名额')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_quotas', to='Professor_Student_Manage.professor', verbose_name='导师')),
                ('subject', models.ForeignKey(limit_choices_to={'subject_type__in': [0, 1]}, on_delete=django.db.models.deletion.CASCADE, to='Enrollment_Manage.subject', verbose_name='硕士专业')),
            ],
            options={
                'verbose_name': '导师硕士专业名额',
                'verbose_name_plural': '导师硕士专业名额',
                'unique_together': {('professor', 'subject')},
            },
        ),
    ]
