# Generated by Django 3.2.8 on 2025-09-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0059_professormasterquota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professormasterquota',
            name='total_quota',
            field=models.IntegerField(default=0, verbose_name='总招生名额'),
        ),
    ]
