# Generated by Django 3.2.8 on 2025-09-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0060_alter_professormasterquota_total_quota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professormasterquota',
            name='beijing_used_quota',
        ),
        migrations.RemoveField(
            model_name='professormasterquota',
            name='yantai_used_quota',
        ),
        migrations.AddField(
            model_name='professormasterquota',
            name='beijing_quota',
            field=models.IntegerField(default=0, verbose_name='北京可用名额'),
        ),
        migrations.AddField(
            model_name='professormasterquota',
            name='yantai_quota',
            field=models.IntegerField(default=0, verbose_name='烟台可用名额'),
        ),
        migrations.AlterField(
            model_name='professormasterquota',
            name='total_quota',
            field=models.IntegerField(default=0, verbose_name='硕士总招生名额'),
        ),
    ]
