# Generated by Django 3.2.8 on 2025-09-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0061_auto_20250917_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='alternate_rank',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='候补顺序'),
        ),
    ]
