# Generated by Django 3.2.8 on 2025-09-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0062_student_alternate_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_signate_giveup_table',
            field=models.BooleanField(default=False, verbose_name='是否签名放弃说明表'),
        ),
    ]
