# Generated by Django 3.2.8 on 2026-03-28 04:15

import Professor_Student_Manage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0068_professorprofilesection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='department_position',
            field=models.IntegerField(choices=[[0, '非审核人'], [1, '方向审核人(北京)'], [2, '方向审核人(烟台)']], default=0, verbose_name='是否为审核人'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='proposed_quota_approved',
            field=models.BooleanField(default=False, verbose_name='开放被选择资格'),
        ),
        migrations.AlterField(
            model_name='professorprofilesection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_year',
            field=models.PositiveIntegerField(default=Professor_Student_Manage.models.get_default_admission_year, verbose_name='届别'),
        ),
        migrations.AlterField(
            model_name='student',
            name='candidate_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='考生编号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='final_rank',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='综合排名'),
        ),
    ]
