# Generated by Django 3.2.8 on 2026-03-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0069_auto_20260328_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='heat_display_enabled',
            field=models.BooleanField(default=True, verbose_name='前端是否显示热度'),
        ),
        migrations.AddField(
            model_name='professor',
            name='manual_heat_level',
            field=models.CharField(blank=True, choices=[('低', '低'), ('中', '中'), ('高', '高'), ('很高', '很高')], max_length=10, null=True, verbose_name='手动热度等级'),
        ),
        migrations.AddField(
            model_name='professor',
            name='manual_heat_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='手动热度指数'),
        ),
        migrations.CreateModel(
            name='ProfessorHeatDisplaySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_professor_heat', models.BooleanField(default=True, verbose_name='前端是否显示导师热度')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '导师热度显示配置',
                'verbose_name_plural': '导师热度显示配置',
            },
        ),
    ]
