# Generated by Django 3.2.8 on 2023-08-13 17:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Professor_Student_Manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfessorChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_order', models.CharField(choices=[['1', '第一志愿'], ['2', '第二志愿'], ['3', '第三志愿']], default='1', max_length=1, verbose_name='志愿顺序')),
                ('status', models.CharField(choices=[['1', '已同意'], ['2', '已拒绝'], ['3', '请等待']], default='3', max_length=1, verbose_name='状态')),
                ('chosen_by_professor', models.BooleanField(default=False, verbose_name='是否选中')),
                ('submit_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交时间')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='选中时间')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Professor_Student_Manage.professor', verbose_name='导师姓名')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Professor_Student_Manage.student', verbose_name='学生姓名')),
            ],
            options={
                'verbose_name': '学院师生互选情况',
                'verbose_name_plural': '学院师生互选情况',
            },
        ),
    ]
