# Generated by Django 3.2.8 on 2023-08-28 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Select_Information', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofessorchoice',
            name='choice_order',
        ),
    ]
