# Generated by Django 3.2.8 on 2024-03-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Select_Information', '0004_alter_studentprofessorchoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofessorchoice',
            name='status',
            field=models.IntegerField(choices=[[1, '已同意'], [2, '已拒绝'], [3, '请等待'], [4, '已取消']], default=3, verbose_name='状态'),
        ),
    ]
