# Generated by Django 3.2.8 on 2024-03-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Select_Information', '0005_alter_studentprofessorchoice_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.DateTimeField(verbose_name='开放时间')),
                ('close_time', models.DateTimeField(verbose_name='关闭时间')),
            ],
        ),
    ]
