# Generated by Django 3.2.8 on 2024-03-28 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Select_Information', '0006_selectiontime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selectiontime',
            options={'verbose_name': '学院师生互选时间设置', 'verbose_name_plural': '学院师生互选时间设置'},
        ),
    ]
