# Generated by Django 3.2.8 on 2024-09-26 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0046_auto_20240924_0328'),
        ('Select_Information', '0007_alter_selectiontime_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=500, verbose_name='文件ID')),
                ('review_status', models.BooleanField(default=False, verbose_name='审核状态')),
                ('review_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Professor_Student_Manage.professor', verbose_name='导师')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer', to='Professor_Student_Manage.professor', verbose_name='审核人')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Professor_Student_Manage.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '审核记录',
                'verbose_name_plural': '审核记录',
            },
        ),
    ]
