# Generated by Django 3.2.8 on 2024-09-26 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Student_Manage', '0046_auto_20240924_0328'),
        ('Select_Information', '0008_reviewrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrecord',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_records', to='Professor_Student_Manage.professor', verbose_name='导师'),
        ),
    ]
