# Generated by Django 3.2.8 on 2024-09-26 07:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Select_Information', '0009_alter_reviewrecord_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrecord',
            name='status',
            field=models.IntegerField(choices=[(1, '已通过'), (2, '已驳回'), (3, '待审核')], default=3, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='reviewrecord',
            name='submit_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交时间'),
        ),
    ]
