# Generated by Django 3.2.8 on 2025-03-24 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Select_Information', '0010_auto_20240926_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrecord',
            name='review_status',
        ),
    ]
