# Generated by Django 3.2.8 on 2025-03-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Select_Information', '0011_remove_reviewrecord_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrecord',
            name='review_status',
            field=models.BooleanField(default=False, verbose_name='审核状态'),
        ),
    ]
