# Generated by Django 3.2.8 on 2023-08-13 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Professor_Student_Manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionQuotaApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_quota', models.IntegerField(default=0, verbose_name='学硕名额')),
                ('professional_quota', models.IntegerField(default=0, verbose_name='专硕名额')),
                ('doctor_quota', models.IntegerField(default=0, verbose_name='博士名额')),
                ('status', models.CharField(choices=[('0', '等待审核'), ('1', '通过'), ('2', '拒绝'), ('3', '已取消')], default='0', max_length=1, verbose_name='审核状态')),
                ('submit_date', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('reviewed_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_quota_approvals', to='Professor_Student_Manage.professor', verbose_name='导师姓名')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to='Professor_Student_Manage.professor', verbose_name='审核人')),
            ],
            options={
                'verbose_name': '导师指标审核',
                'verbose_name_plural': '导师指标审核',
            },
        ),
    ]
