# Generated by Django 3.2.8 on 2024-02-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor_Quota_Review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionquotaapproval',
            name='professional_yt_quota',
            field=models.IntegerField(default=0, verbose_name='烟台专硕名额'),
        ),
        migrations.AlterField(
            model_name='admissionquotaapproval',
            name='professional_quota',
            field=models.IntegerField(default=0, verbose_name='北京专硕名额'),
        ),
    ]
